name: Run Scraper

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:         

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install playwright
          playwright install chromium
          playwright install-deps

      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          HEADLESS: "true"
          COOKIES: ${{ secrets.COOKIES }}
          # LINKEDIN_COOKIES_JSON: ${{ secrets.LINKEDIN_COOKIES_JSON }} no need rn, doing bot fill :(
        run: |
          python crawler.py